services:
  postgres:
    image: postgres:16
    container_name: lims_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "!@$$PostgreSQL16$$@!"
      POSTGRES_DB: lims_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    image: ${DOCKER_USERNAME}/lims-backend:latest
    container_name: lims_backend
    restart: always
    environment:
      PORT: 3168
      HOST: 0.0.0.0
      NODE_ENV: production
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: lims_db
      DB_USER: postgres
      # DB_PASSWORD and JWT_SECRET are fetched from AWS Secrets Manager
      # DB_PASSWORD: ...
      # JWT_SECRET: ...
      CORS_ORIGIN: "http://${EC2_HOST}:80"
    command: npm start
    logging:
      driver: awslogs
      options:
        awslogs-region: ap-south-1
        awslogs-group: /ec2/lims-backend
        awslogs-create-group: "true"
    depends_on:
      - postgres
    volumes:
      - lims_uploads:/app/uploads

  frontend:
    image: ${DOCKER_USERNAME}/lims-frontend:latest
    container_name: lims_frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data:
  lims_uploads:
